### ISSUE TITLE
Bug in column_trans module

### ISSUE THREAD

**Issue by glen-mac** [nccgroup/featherduster#57]
Running the column_trans module fails. I'll try my hand at making a fix but just letting others know.

```
↳ python featherduster.py     
Welcome to FeatherDuster!

To get started, use 'import' to load samples.
Then, use 'analyze' to analyze/decode samples and get attack recommendations.
Next, run the 'use' command to select an attack module.
Finally, use 'run' to run the attack and see its output.

For a command reference, press Enter on a blank line.

FeatherDuster> import singlefile
Please enter the filename you want to open: railfence.crypt

FeatherDuster> analyze 
[+] Analyzing samples...
[+] Messages may be encrypted with a stream cipher or simple XOR.
[!] Individual messages have failed statistical tests for randomness.
[!] This suggests weak crypto is in use.
[!] Consider running single-byte or multi-byte XOR solvers.
[!] Ciphertexts match the frequency distribution of a transposition-only ciphertext.
[!] Consider using transposition solvers (rail fence, columnar transposition, etc)

[+] Suggested modules:
   alpha_shift          - A brute force attack against an alphabetic shift cipher. 
   base_n_solver        - A solver for silly base-N encoding obfuscation.          
   single_byte_xor      - A brute force attack against single-byte XOR encrypted ciphertext.
   column_trans         - A brute force attack against columnar transposition ciphers.
   multi_byte_xor       - A brute force attack against multi-byte XOR encrypted ciphertext.
   many_time_pad        - A statistical attack against keystream reuse in various stream ciphers.
   vigenere             - A module to break vigenere ciphers using index of coincidence for key length detection and frequency analysis.

FeatherDuster> use column_trans                                                                      

FeatherDuster> run
Best results of columnar transposition solve:
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/ishell/console.py", line 102, in loop
    self.walk_and_run(input_)
  File "build/bdist.linux-x86_64/egg/ishell/console.py", line 69, in walk_and_run
    self.walk(command, 0, run=True, full_line=command)
  File "build/bdist.linux-x86_64/egg/ishell/console.py", line 54, in walk
    return cmd.complete(line_commands[1:], buf, state, run, full_line)
  File "build/bdist.linux-x86_64/egg/ishell/command.py", line 69, in complete
    return self.run(full_line.rstrip())
  File "featherduster.py", line 288, in run
    feathermodules.results = feathermodules.selected_attack['attack_function'](feathermodules.samples)
  File "/home/glenn/featherduster/feathermodules/classical/columnar_transposition.py", line 11, in break_columnar_transposition
    print '\n'.join(results)
TypeError: sequence item 0: expected string, list found
```

**Comment by glen-mac** [comment]
Made the fix - making pull request.

**Comment by glen-mac** [comment]
Creating pull request

https://github.com/nccgroup/featherduster/pull/58

**Comment by unicornsasfuel** [comment]
This seems to be an issue with the expected output of feathermodules and the output from the columnar transposition solver. The solver returns a list of best answers for each sample it operates on, and FeatherDuster gets confused, as it is asked to operate on the list as if it were a string. I'll fix this.
